name: Build

on: [push]

env:
  PROJECT_ID: ${{ secrets.STG_GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.STG_GKE_CLUSTER }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - run: |
          export APP_COMMIT_INFO=$(git show -s --format="hash: %h, branch: $(git rev-parse --abbrev-ref HEAD), date: %aI") && sed -i "s|__APP_COMMIT_INFO__|${APP_COMMIT_INFO}|g" public/index.html

      - name: Build docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.magnacerta.io
          repository: magna-certa/app-admin-ui
          tags: latest
          push: true

      - name: Install kubectl command
        uses: azure/setup-kubectl@v1
        id: install

      - name: Setup gcloud cli
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: ${{ secrets.STG_GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.STG_GKE_SA_KEY }}
          export_default_credentials: true

      - name: Prepare K8s config
        run: |
          gcloud container clusters get-credentials ${GKE_CLUSTER} --region us-central1 --project ${PROJECT_ID}
      - name: Deploy pod
        run: |
          kubectl apply -f k8s/ --namespace paloma-project
      - name: Rollout pod to force pull latest
        run: |
          kubectl rollout restart deployment/app-admin-ui --namespace paloma-project
      - name: Cleanup
        if: always()
        run: rm -rf ~/.kube ~/.config
        env:
          status: ${{job.status}}
